services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile

  shortenerdb:
    image: mcr.microsoft.com/mssql/server

volumes:
    shortenerdb-data:
